### ISSUE TITLE
Non-integer step size optimisation error on HPC

### ISSUE THREAD

**Issue by hamishbeath** [CLOVER-energy/CLOVER#135]
### Describe the bug
An error is arising whilst running optimisations on the HPC. This recurring error seems to be related to non-integer inputs or inputs as zero. The error occurs when moving from one optimisation step to the next. It is likely that the error occurs when the minimum PV or storage size is set to zero.

### Expected behaviour
The optimisations should run regardless of non-integer step sizes or minima of zero. 

### Screenshots
Print out from example optimisation run:
system_details: SystemDetails(diesel_capacity=0.0, end_year=5, final_converter_sizes={}, final_cw_pvt_size=None, final_hw_pvt_size=None, final_num_buffer_tanks=None, final_num_clean_water_tanks=None, final_num_hot_water_tanks=None, final_pv_size=0.475, final_storage_size=1.2885906130243385, initial_converter_sizes={}, initial_cw_pvt_size=None, initial_hw_pvt_size=None, initial_num_buffer_tanks=None, initial_num_clean_water_tanks=None, initial_num_hot_water_tanks=None, initial_pv_size=0.5, initial_storage_size=1.4000000000000001, required_feedwater_sources=None, start_year=0, file_information=None)
28/10/2022 06:53:28 PM: Angola_2020_ssp2_tier3_SHS_clover_9: INFO: Single-line optimisation to be carried out.
28/10/2022 06:53:28 PM: Angola_2020_ssp2_tier3_SHS_clover_9: INFO: Increasing storage size.
28/10/2022 06:53:28 PM: Angola_2020_ssp2_tier3_SHS_clover_9: ERROR: [91mAn unexpected error occurred running a CLOVER optimisation. See logs/clover.log for details: range() arg 3 must not be zero[0m

**Comment by BenWinchester** [comment]
@hamishbeath , do you remember if we resolved this?

**Comment by hamishbeath** [comment]
Hi – so we definitely fixed something… I am using non integer step sizes on the HPC so it works somehow but I can’t remember if it was a hack?

Would you like me to go onto the HPC and look at my set up?

From: Ben Winchester ***@***.***>
Date: Thursday, 2 February 2023 at 15:55
To: CLOVER-energy/CLOVER ***@***.***>
Cc: Hamish Beath ***@***.***>, Mention ***@***.***>
Subject: Re: [CLOVER-energy/CLOVER] Non-integer step size optimisation error on HPC (Issue #135)

@hamishbeath<https://github.com/hamishbeath> , do you remember if we resolved this?
