### ISSUE TITLE
Fixed Costs

### ISSUE THREAD

**Issue by BenWinchester** [CLOVER-energy/CLOVER#153]
### Issue
Currently, all costs within CLOVER are tied to components. Whether this is directly, e.g., the cost of installing a specific component, or whether this is indirectly, e.g., the `misc` costs within the `finance_inputs.yaml` which are scaled with the capacity of (number of) PV collectors installed. There is no way currently to include some static costs.

#### Importance and relevance
Static costs crop up throughout energy-system modelling:
* The land/area needed for installing a system may come as a pre-purchased amount, which doesn't scale with the size of the system, but the cost of which needs to be included in $lcue$ and $total$ $cost$ calculations;
* Installation costs which are fixed, e.g., construction of the setup or delivery of large components which potentially necessitate some fixed cost. E.G., a van for delivering 10 solar panels is likely the same as that for 1 solar panel, so the cost should scale accordingly.

### Proposal
A fixed _misc_ cost should be included in the `finance_inputs.yaml` file:
```yaml
misc:
  capacity_cost: 0  # [$/kWp]
  fixed_cost: 0  # [$]
```
where the `fixed_cost` is added at the start of the simulation/optimisation period, and the `capacity_cost` scales with the capacity as per the old `cost` variable:
```diff
misc:
- cost: 0 # [$]
+ capacity_cost: 0  # [$/kW]
+ fixed_cost: 0  # [$]
```

Alternatives include:
* A _"hacky"_ solution, whereby these costs are included as household costs, or as some tweak to the installation costs;
* Not including these costs.

**Comment by BenWinchester** [comment]
@phil-sandwell and @hamishbeath ,

This issue was raised in response to costs which @palomaortegaa needs to include in her calculations. I've tagged you both to see whether you are happy with this approach. It makes logical sense to me, but I'm happy to look into an alternative :smiley:

**Comment by hamishbeath** [comment]
This is the way to go, on CLOVER 4 I used a similar hack to add non-capacity indexed costs. It may also be good to have costs that scale with the battery size as opposed to the PV, but we can think about that another time...

**Comment by BenWinchester** [comment]
This is being introduced in `v5.0.7b2`, a second beta "pre-release" of `v5.0.7` for @palomaortegaa to use :smiley:

Using `cost` in lieu of `fixed_cost` and `capacity_cost` will be supported for now but with warning that this will be deprecated in order to encourage users to update their inputs. This can be done by deleting their `finance_inputs.yaml` file and running `new-clover-location <location_name> --update` to reintroduce the up-to-date file.
