### ISSUE TITLE
Tracking solar panel

### ISSUE THREAD

**Issue by BenWinchester** [CLOVER-energy/CLOVER#209]
### Issue
When running CLOVER, there is scope within the `solar_generation_inputs.yaml` file to consider multiple types of PV panel. However, all of these panels are non-tracking (i.e., mounted at fixed angles). Ideally, to include the full range of panels available commercially, tracking panels should be included.

### Proposal
* The inputs file should contain provision for tracking panels,
* The code which calls renewables.ninja should be updated to enable this to be done.

In terms of alternatives, there are two:
* 🏖️ _the easy option_ is just doing nothing, i.e., leaving the code just having fixed-mounted panels,
* 🗻 _the hard option_ is switching the code away from using renewables.ninja all-together and doing the calculations for performance locally. This will mean local calculations for both performance and tracking.

**Comment by hamishbeath** [comment]
I wondering if there are use cases for tracking PV in the context of community scale energy systems? If unlikely, this could be a low priority? Additionally, would be good to establish the way in which RN calculates tracked PV output and whether it is specific to certain kinds of tracking systems etc.
