### ISSUE TITLE
Prioitise self-generation bug

### ISSUE THREAD

**Issue by BenWinchester** [CLOVER-energy/CLOVER#54]
### Describe the bug
When running CLOVER, there are two possible flows for how the code selects its source of power, which are set within the `scenario_inputs.yaml` file:
- `prioiritise_self_generation: true`, where CLOVER should attempt to get power from the solar and storage first,
- and `prioritise_self_generation: false`, where CLOVER should get its power from the grid first.

However, when running a CLOVER `optimisation`, there is **no difference** between these two flows, with the same outputs being selected despite the second scenario being expected to produce systems with a lower renewable capacity due to the reliance on the grid as the primary source of power.

### To Reproduce
1. Set up two identical scenarios in the `scenario_inputs.yaml` file with the only difference between the two being the `prioritise_self_generation` flag;
2. Set up two identical optimisations in the `optimisation_inputs.yaml` file with the only difference between the two being the scenario that each uses;
3. Run an optimisation with `python -u -m src.clover --location <location_name> --optimisation`;
4. See error.

### Expected behaviour
The two scenario should produce different results, with the `true` scenario selecting a higher renewable capacity and the `false` scenario selecting a smaller renewable capacity.

### Screenshots
Screenshots are not needed to explain this problem.

### Desktop
**(please complete the following information)**
 - OS: Linux, applies to all
 - Installation setup: downloaded source from GitHub
 - Version: 5.0.1b1
 - Branch: `dev`

### Modifications
This version is up-to-date with `origin/dev`.

**Comment by BenWinchester** [comment]
This issue appears to be different than what was expected, with a dataframe memory-assignment issue:
```
Traceback (most recent call last):
  File "/home/bewinche/anaconda3/envs/py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/bewinche/anaconda3/envs/py37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bewinche/modelling/CLOVER-energy/src/clover/__main__.py", line 1256, in <module>
    main(sys.argv[1:])
  File "/home/bewinche/modelling/CLOVER-energy/src/clover/__main__.py", line 1196, in main
    electric_yearly_load_statistics,
  File "/home/bewinche/modelling/CLOVER-energy/src/clover/optimisation/optimisation.py", line 1421, in multiple_optimisation_step
    yearly_electric_load_statistics,
  File "/home/bewinche/modelling/CLOVER-energy/src/clover/optimisation/optimisation.py", line 1077, in _optimisation_step
    yearly_electric_load_statistics,
  File "/home/bewinche/modelling/CLOVER-energy/src/clover/optimisation/optimisation.py", line 505, in _simulation_iteration
    wind_speed_data,
  File "/home/bewinche/modelling/CLOVER-energy/src/clover/simulation/energy_system.py", line 1446, in run_simulation
    start_hour=start_hour,
  File "/home/bewinche/modelling/CLOVER-energy/src/clover/simulation/storage.py", line 641, in get_electric_battery_storage_profile
    grid_energy: pd.DataFrame = grid_profile.mul(load_energy)  # type: ignore
  File "/home/bewinche/anaconda3/envs/py37/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 196, in flex_wrapper
    return op(self, other)
  File "/home/bewinche/anaconda3/envs/py37/lib/python3.7/site-packages/pandas/core/ops/common.py", line 69, in new_method
    return method(self, other)
  File "/home/bewinche/anaconda3/envs/py37/lib/python3.7/site-packages/pandas/core/arraylike.py", line 112, in __rmul__
    return self._arith_method(other, roperator.rmul)
  File "/home/bewinche/anaconda3/envs/py37/lib/python3.7/site-packages/pandas/core/frame.py", line 6864, in _arith_method
    self, other = ops.align_method_FRAME(self, other, axis, flex=True, level=None)
  File "/home/bewinche/anaconda3/envs/py37/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 307, in align_method_FRAME
    right, join="outer", axis=axis, level=level, copy=False
  File "/home/bewinche/anaconda3/envs/py37/lib/python3.7/site-packages/pandas/core/frame.py", line 4687, in align
    broadcast_axis=broadcast_axis,
  File "/home/bewinche/anaconda3/envs/py37/lib/python3.7/site-packages/pandas/core/generic.py", line 8600, in align
    fill_axis=fill_axis,
  File "/home/bewinche/anaconda3/envs/py37/lib/python3.7/site-packages/pandas/core/generic.py", line 8714, in _align_series
    fdata = fdata.reindex_indexer(join_index, lidx, axis=bm_axis)
  File "/home/bewinche/anaconda3/envs/py37/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 677, in reindex_indexer
    indexer, fill_value=fill_value, only_slice=only_slice
  File "/home/bewinche/anaconda3/envs/py37/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 782, in _slice_take_blocks_ax0
    self._make_na_block(placement=mgr_locs, fill_value=fill_value)
  File "/home/bewinche/anaconda3/envs/py37/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 836, in _make_na_block
    block_values = np.empty(block_shape, dtype=dtype)  # type: ignore[arg-type]
numpy.core._exceptions.MemoryError: Unable to allocate 57.2 GiB for an array with shape (87599, 87600) and data type float64
```

This is not the bug that was initially reported to the development team, but is still a bug in the same area of the code.

**Comment by BenWinchester** [comment]
This branch has actually managed to remain untested and made it into production code, suggest a new release to fix this bug tagged 5.0.1 or 5.0.0.post1 or .post 2. @phil-sandwell ?

**Comment by phil-sandwell** [comment]
I've run some optimisations to test this and these changes appear to working as desired. For a system with the grid, solar and battery storage under `prioritisate_self_generation = true` or `false`:
- Optimising a system where grid reliability is less than the desired overall system reliability yields the expected results: the system with `false` relies more heavily on grid energy, and `true` relies more heavily on self-generation.
- Optimising a system where grid reliability is greater than the desired overall system reliability yields the expected results: for both `true` and `false`, no PV or storage is implemented. 

I think this means it's okay to integrate this into a new release. Up to you @BenWinchester as to whether you think it should be (now) 5.0.2 or .post1 (etc.).

**Comment by phil-sandwell** [comment]
Reopening this issue as a new bug has been found. When `prioritise self-generation: false` an error is occurring in which the PV and storage sizes are increasing (expected) but the blackout threshold of a system during simulation is not (unexpected). 

Under my example simulations, a system has a set grid reliability (e.g. 20 hours/day) and is tasked with providing increasingly high levels of reliability (e.g. `blackouts: 0.3, 0.2, 0.1, 0.05`). The first few optimisations will complete but then a later one will fail. 

Looking into the log file (attached) the PV and storage sizes increase as expected, as do their costs/emissions/etc., but `blackouts` is stuck at `0.096` regardless of system size. It therefore never completes the optimisation and runs indefinitely.

@BenWinchester what do you think could be causing this? Could it be that the increase in PV/storage size is not being passed on to the simulation, meaning no increase in demand satisfaction and therefore the blackouts stays the same?

[UP_clover.log](https://github.com/CLOVER-energy/CLOVER/files/9027313/UP_clover.log)

**Comment by BenWinchester** [comment]
Hi @phil-sandwell , an interesting bug!

#### Lots of optimisations
It looks like there are several optimisations in that file: the first two/three work fine, and a sufficient system is determined. It looks like the final one, where it's aiming perhaps for `0.05` and never getting more reliable than `0.89` or `0.88` (potentially a rounding error between those two numbers, different issue).

Not really sure, but definitely worth investigating :smile:

**Comment by BenWinchester** [comment]
# Testing approach
## Issue
The fixing of this bug affects the automated integration testing brought in by #61 as part of #86 . As it stands, the automated `pytest` changes will need to be updated in order for this bug :bug: to be merged into the `master` branch.

## Approach
1. Update the automated tests on the `dev` branch. On the `dev` branch, the automated tests need to be updated to reflect this bug. This will involve
    1. Updating the `scenario_inputs.yaml` file in the `temp_location` directory in order to contain a single scenario. Only one scenario is needed in this file, and having multiple brings in unnecessary changes when updates to the code take place;
    2. Adding a `prioritise_self_generation` flag to the helper script in the integration testing python file so that the tests can decide whether to run with this flag set to `true` or `false` in the scenarios file;
    3. Adding an additional 15 or 16 tests so that the tests consist of all possible combinations of:
        1. PV
        2. Storage
        3. Diesel
        4. Grid
        5. and prioritsation of self-generation;
    4. Opening an merging a pull request into the `dev` branch, or directly committing to the `dev` branch, to update the tests;
2. Merge the `dev` branch into the `54-...` branch in order for these additional and updated tests to now run on the pull request #96 ;
3. Update the affected tests so that the results match and the tests pass by changing the values that are used in the affected tests;
4. Approve and merge pull request #96 ;
5. Open and merge a pull request into `master`:
6. Once merged, generate a release for the code. This will involve:
    1. Installing the python packages `twine` and `build` via
       ```bash
       python -m pip install twine build
       ```
    2. Building the code locally by running
       ```bash
       python -m build
       ```
    3. Uploading the generated package files to `pypi` via:
       ```bash
       python -m twine upload dist/*
       ```
       where the username is `__token__` and the password is your access token for `pypi`;
    4. Generating a release on Github on the rhs of the main landing page for the repository, with the "target" set to `master` and the "attached binaries" / "optional files" the generated files (the `.whl` wheel etc.) within the `./dist` directory.
