### ISSUE TITLE
🎨 Shorten CLOVER CLI arguments

### ISSUE THREAD

**Issue by BenWinchester** [CLOVER-energy/CLOVER#83]
### Issue
The number of different technologies in CLOVER is resulting in cumbersome CLI arguments: `--hot-water-pv-t-system-size`, `--num-clean-water-tanks` etc. Whilst __fine__, it is adding unnecessary complication to the code and is frustrating to use.

This problem exists within the standard codebase, but is likely to be exacerbated as the number of flags and technologies continues to grow and expand with #76 and future changes such as #41 .

### Proposal
Either:
* Shorter command-line arguments should be introduced to **replace** the current command-line arguments;
* Shorter command-line arguments should be introduced to work **alongside** the current command-line arguments.

There are no alternatives beyond simply putting up with this.

### Note
**Additional context**
This issue will impact the functionality of CLOVER and how current users use it. It hence a **high-impact** feature.

**Comment by BenWinchester** [comment]
## Proposed new arguments
| Long (old) argument | Short version | Description |
| --- | --- | --- |
| `--analyse` | `-a` | If specified, plots will be generated and saved and key results will be calculated and saved for the simulation. |
| `--clean-water-pvt-system-size` | `-cwpvt` | The size of the PV-T system being modelled, associated with the clean-water supply system, in PV-T panel units. |
| `--electric-load-profile` | `-el` | The name of the load profile to use for the run. This overrides CLOVER's in-built load-profile generation. |
| `--hot-water-pvt-system-size` | `-hwpvt` | The size of the PV-T system being modelled, associated with the hot-water supply system, in PV-T panel units. |
| `--location` | `-l` | The name of the location for which to run CLOVER. |
| `--num-clean-water-tanks` | `-ncwt` | The number of clean-water tanks to be included in the system. |
| `--num-hot-water-tanks` | `-nhwt` | The number of hot-water tanks to be included in the system. |
| `--optimisation` | `-opt` | If specified, CLOVER will carry out optimisations in accordance with the `optimisation_inputs` file. |
| `--output` | `-o` | The location of the output file in which simulation data will be saved. |
| `--pv-system-size` | `-pv` | The size of the PV system being modelled in PV panel units, defaulting to kWp. |
| `--refetch` | **no proposed change** | If specified, CLOVER will refetch the various profiles used from the renewables.ninja API. Otherwise, existing profiles will be used if present. |
| `--regenerate` | **no proposed change** | If specified, CLOVER will regenerate the various profiles used. Otherwise, existing profiles will be used if present. |
| `--scenario` | `-s` | The name of the scenario to use for the run. |
| `--simulation` | `-sim` | If specified, CLOVER will carry out a single simulation. |
| `--skip-plots` | `-sp` | If specified, plots will be skipped. Note, only affects cases where analysis has been requested; plot generation cannot be carried out without analysis. |
| `--storage-system-size` | `-b` (for battery) | The size of the battery system being modelled in battery units, defaulting to kWh. |

**Comment by BenWinchester** [comment]
Implementing the above results in the following help string:
```python
$ python -u -m src.clover --help
usage: __main__.py [-h] [--location LOCATION] [--refetch] [--regenerate]
                   [--electric-load-profile ELECTRIC_LOAD_PROFILE]
                   [--output OUTPUT] [--pv-system-size PV_SYSTEM_SIZE]
                   [--scenario SCENARIO] [--storage-size STORAGE_SIZE]
                   [--num-clean-water-tanks NUM_CLEAN_WATER_TANKS]
                   [--clean-water-pvt-system-size CLEAN_WATER_PVT_SYSTEM_SIZE]
                   [--num-hot-water-tanks NUM_HOT_WATER_TANKS]
                   [--hot-water-pvt-system-size HOT_WATER_PVT_SYSTEM_SIZE]
                   [--simulation] [--analyse] [--skip-plots] [--optimisation]

optional arguments:
  -h, --help            show this help message and exit

mandatory arguments:
  --location LOCATION, -l LOCATION
                        The name of the location for which to run CLOVER.

profile arguments:
  --refetch             If specified, CLOVER will refetch the various profiles
                        used from the renewables.ninja API. Otherwise,
                        existing profiles will be used if present.
  --regenerate          If specified, CLOVER will regenerate the various
                        profiles used. Otherwise, existing profiles will be
                        used if present.

simulation and optimisation arguments:
  --electric-load-profile ELECTRIC_LOAD_PROFILE, -el ELECTRIC_LOAD_PROFILE
                        The name of the load profile to use for the run. This
                        overrides CLOVER's in-built load-profile generation.
  --output OUTPUT, -o OUTPUT
                        The location of the output file in which simulation
                        data will be saved.
  --pv-system-size PV_SYSTEM_SIZE, -pv PV_SYSTEM_SIZE
                        The size of the PV system being modelled in PV panel
                        units, defaulting to kWp.
  --scenario SCENARIO, -s SCENARIO
                        The name of the scenario to use for the run.
  --storage-size STORAGE_SIZE, -b STORAGE_SIZE
                        The size of the battery system being modelled in
                        battery units, defaulting to kWh.

clean-water-only arguments:
  --num-clean-water-tanks NUM_CLEAN_WATER_TANKS, -ncwt NUM_CLEAN_WATER_TANKS
                        The number of clean-water tanks to be included in the
                        system.
  --clean-water-pvt-system-size CLEAN_WATER_PVT_SYSTEM_SIZE, -cwpvt CLEAN_WATER_PVT_SYSTEM_SIZE
                        The size of the PV-T system being modelled, associated
                        with the clean-water supply system, in PV-T panel
                        units.

hot-water-only arguments:
  --num-hot-water-tanks NUM_HOT_WATER_TANKS, -nhwt NUM_HOT_WATER_TANKS
                        The number of hpt-water tanks to be included in the
                        system.
  --hot-water-pvt-system-size HOT_WATER_PVT_SYSTEM_SIZE, -hwpvt HOT_WATER_PVT_SYSTEM_SIZE
                        The size of the PV-T system being modelled, associated
                        with the hot-water supply system, in PV-T panel units.

simulation-only arguments:
  --simulation, -sim    If specified, CLOVER will carry out a single
                        simulation.
  --analyse, -a         If specified, plots will be generated and saved and
                        key results will be calculated and saved for the
                        simulation.
  --skip-plots, -sp     If specified, plots will be skipped. Note, only
                        affects cases where analysis has been requested; plot
                        generation cannot be carried out without analysis.

optimisation-only arguments:
  --optimisation, -opt  If specified, CLOVER will carry out optimisations in
                        accordance with the `optimisation_inputs` file.
```

**Comment by phil-sandwell** [comment]
These all look good to me, I think the contractions are all intuitive. Shame about needing to use `b` for `--storage-system-size` but I think it's the right decision to use `s` for `--scenario`.
