### ISSUE TITLE
📚 Submission to the Journal of Open Source Software

### ISSUE THREAD

**Issue by phil-sandwell** [CLOVER-energy/CLOVER#97]
### Issue
CLOVER is an academic software and as such should have a formal presence in the literature. The [Journal of Open Source Software](http://joss.theoj.org/) (JOSS) is a developer friendly journal for research software packages. CLOVER already fulfils many of the requirements necessary to submit a paper to JOSS and that submission could be used as the reference for future uses of CLOVER in other journals. 

### Proposal
We should submit a paper describing CLOVER to JOSS. The submission requirements are described [here](https://joss.readthedocs.io/en/latest/submitting.html#typical-paper-submission-flow). This will require:

- Writing a paper of between 250-1000 words (`paper.md`)
- Compiling a bibliography (`references.bib`)
- Checking that the paper compiles using the [Open Journals PDF Generator](https://github.com/marketplace/actions/open-journals-pdf-generator)

This issue should be addressed on the `publish` branch. 

### Note
I have a draft of a JOSS paper relevant to a previous version of CLOVER which I will update to reflect the current version and structure.

**Comment by BenWinchester** [comment]
As part of this/one this is complete, we should update the `CITATION.cff` file with the information about the paper. Example [here](https://github.com/citation-file-format/citation-file-format/blob/main/examples/1.1.0/software-with-reference/CITATION.cff) :smile:

**Comment by phil-sandwell** [comment]
This issue is now being addressed in #127.
